config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"

  
  # get 'search', to: 'homes#search'

  # get '', to: 'search#search', as: 'search'

  resources :homes, only: [:index] do
    collection do
      get 'filter'
      get 'select_location'
    end
  end

  devise_scope :user do
    get "user/profile" => "users#profile",as: "profile_user"
  end

  resources :users do
    resources :addresses
  end
  get '/search', to: 'restaurants#search', as: 'search_restaurants'

  resources :restaurants do 
    collection do
      get 'search'
      get 'suggestions'
      get 'search_by_restaurents'
      get 'search_by_dish'
    end
  end

  resources :cart_items do
    member do 
      post :increment
      post :decrement
    end
  end

  resources :orders do
  end

  resources :order_items do
  end


end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :cart


  def self.ransackable_attributes(auth_object = nil)
    ["cart_id", "created_at", "food_item_id", "id", "quantity", "updated_at"]
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
  def index
		if current_user == nil
			redirect_to new_user_session_path
		else
			@user = current_user
      @addresses = @user.addresses
			@cart= @user.cart || @user.create_cart
			@cart_items = @cart.cart_items.includes(:food_item)
		end
  end

  def create
      if current_user == nil
        redirect_to new_user_session_path
      else
      @user = current_user
      @item = FoodItem.find(params[:item_id])
      @cart= @user.cart || @user.create_cart
      @cart_item = @cart.cart_items.create(:food_item_id => @item.id,quantity:"1")
      redirect_to restaurant_path(@item.restaurant)
    end
  end

	def increment
    @cart= current_user.cart
    @food_item = FoodItem.find(params[:id])
    @cart_item = CartItem.find_by(cart_id: @cart.id, food_item_id: @food_item.id)
		@cart_item.increment!(:quantity)
    redirect_back(fallback_location: root_path)
  end

	def decrement
    @cart= current_user.cart
    @food_item = FoodItem.find(params[:id])
    @cart_item = CartItem.find_by(cart_id: @cart.id, food_item_id: @food_item.id)
    if @cart_item.nil? 
      redirect_back(fallback_location: root_path)
		elsif @cart_item.quantity <=1
      @cart_item.destroy
      redirect_back(fallback_location: root_path)
		else
		  @cart_item.decrement!(:quantity)
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy  
    @user = current_user
    @cart = @user.cart 
    @cart_item = @cart.cart_items.find(params[:id])
    @cart_item.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<%= render 'homes/header' %>

<% if @cart_items.empty? %>
	<div><h2>Cart is Empty</h2></div>
<% else %>
<div class="row" >
	<div class="col-8">
		<h1>Select Addresses</h1>
		<%= form_tag order_items_path, method: :post do %>
			<% @addresses.each do |address| %>
				<label>
					<%= check_box_tag 'selected_address_id', address[:id] %>
					<%= "#{address[:door_number]}, #{address[:street_area]}, #{address[:city]}, #{address[:state]}, #{address[:zipcode]}" %>
				</label>
				<%= link_to 'Edit ', edit_user_address_path(current_user, address) %><br>
				<br>
			<% end %>
		
			<%= submit_tag "Place Order" %>
		<% end %>
		            

  		<br>
  	<%= link_to 'add new address', new_user_address_path(current_user) %>
	</div>
	<div class="col-4">
		<div>
			<% total = 0%>
			<big><%= @cart_items.first.food_item.restaurant.name %> </big><br>
			<small><%= @cart_items.first.food_item.restaurant.area %> </small>
			<div>
				<% @cart_items.each do |cart_item| %>
					<div class="row">
						<div class="col-6"> <%= cart_item.food_item.name %></div>
						<div class="col-1">
							<%= link_to "-", decrement_cart_item_path(cart_item.food_item.id), :class => "button",method: :post  %>
						</div>
						<div class="col-1"><%= cart_item.quantity %></div>
						<div class="col-1">
							<%= link_to "+", increment_cart_item_path(cart_item.food_item.id), :class => "button",method: :post%>
						</div>
						<div class="col-3"> Rs.<%= cart_item.quantity.to_i * cart_item.food_item.price.to_i %></div>
					</div>
					<% total = total.to_i + cart_item.quantity.to_i * cart_item.food_item.price.to_i %>
				<% end %>
			</div>
			<div>
				<h3>billing</h3>
				<div class="row">
					<div class="col-8">
						<p>Total prize </p>
					</div>
					<div class="col-4">Rs. <%= total %></div>
				</div>
				<div>

				</div>
			</div>
		</div>
	</div>
</div>
<% end %>