config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"

  
  # get 'search', to: 'homes#search'

  # get '', to: 'search#search', as: 'search'

  resources :homes, only: [:index] do
    collection do
      get 'filter'
      get 'select_location'
    end
  end

  devise_scope :user do
    get "user/profile" => "users#profile",as: "profile_user"
  end

  resources :users do
    resources :addresses
  end
  get '/search', to: 'restaurants#search', as: 'search_restaurants'

  resources :restaurants do 
    collection do
      get 'search'
      get 'suggestions'
      get 'search_by_restaurents'
      get 'search_by_dish'
    end
  end

  resources :cart_items do
    member do 
      post :increment
      post :decrement
    end
  end

  resources :orders do
  end

  resources :order_items do
  end


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_one :address, as: :addressable, dependent: :destroy
  has_many :food_items, dependent: :destroy
  has_one  :picture, as: :imageable, dependent: :destroy

  scope :by_street_area, ->(location) { joins(:address).where(address: { street_area: location }).distinct }
  scope :price_range, ->(min_price, max_price) { joins(:food_items).where('food_items.price >= ? AND food_items.price <= ?', min_price, max_price) }
  scope :below_price, ->(max_price) { joins(:food_items).where('food_items.price <= ?', max_price).distinct }
  scope :newest_first, -> { order(created_at: :desc) }

  def self.ransackable_attributes(auth_object = nil)
    ["area", "created_at", "id", "name", "spaciality", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["addresses"]
  end

  def self.ransackable_attributes(auth_object = nil)
    super + ['address_id']
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def show
    @locations = Address.locations
    @restaurant = Restaurant.find(params[:id])
    @food_items = @restaurant.food_items

    if user_signed_in? && current_user.cart
      
      cart_items = current_user.cart.cart_items || nil
    else
      cart_items =nil
    end     
   
    if cart_items.nil?
      @cart_food_item_ids = []
    else
      @item_in_cart = cart_items.map { |cart_item| {food_item_id: cart_item.food_item.id, quantity: cart_item.quantity }}  

      @cart_food_item_ids = cart_items.map { |cart_item| cart_item.food_item.id }  
    end
  end

  def suggestions
    restaurant_data = Restaurant.by_street_area(session[:location])
                                .where("name LIKE ?", "%#{params[:query]}%")
                                .limit(10)
                                .pluck(:id, :name)
                                .map { |id, name| { id: id, name: name, table_name: 'restaurant' } }

    dish_data = Category.where("name LIKE ?", "%#{params[:query]}%")
                        .limit(10)
                        .pluck(:id, :name)
                        .map { |id, name| { id: id, name: name, table_name: 'dish' } }

    @suggestions = restaurant_data + dish_data
    respond_to do |format|
      format.html { render 'suggestions', layout: false }
      format.js   # This is for the AJAX request
    end  
  end

  def search
    @categories = Category.all  
    temp_array = session[:resent_search] || []
    session[:resent_search] = temp_array
  end

  def search_by
    city = Address.where(street_area: session[:location]).distinct.pluck(:city).last
    case params[:search_by] || 'Restaurants'

    when 'Restaurants'
      @restaurant = Restaurant.joins(:address).find_by(address: { city: city }, name: params[:query])
      @restaurants = Restaurant.joins(:address).where(address: { city: city }).where('name LIKE ?', "%#{params[:query]}%")
      respond_to do |format|
        format.html { render 'search_by_restaurents' }
        format.js   
      end  
    when 'Dishes'
      # binding.pry
      # restaurants = Restaurant.by_street_area(session[:location]).pluck(:id)
      restaurants=Restaurant.joins(:address).where(address:{city: city}).pluck(:id)
      @food_items = FoodItem.where(restaurant_id: restaurants).where("name LIKE ?", "%#{params[:query]}%")
      respond_to do |format|
        format.html { render 'search_by_dish' }
        format.js   
      end 
    end
  end

  def search_by_restaurents
    temp_object = session[:recent_search] || {}
    @restaurant = Restaurant.find(params[:suggestionId])
    
    unless temp_object.key?(@restaurant.id)
      temp_object[@restaurant.id] = {
        id: @restaurant.id,
        name: @restaurant.name,
        table_name: 'restaurant'
      }
      session[:recent_search] = temp_object
    end
    respond_to do |format|
      format.html { render 'search_by_restaurents' }
      format.js   
    end  
  end

  def search_by_dish
    @dish = Category.find(params[:suggestionId])
    city = Address.where(street_area: session[:location]).distinct.pluck(:city).last
    restaurants=Restaurant.joins(:address).where(address:{city: city})
    @food_items = FoodItem.joins(:restaurant, :category).where(category: { id:@dish.id , restaurants: { id: restaurants.map(&:id) } })
    respond_to do |format|
      format.html { render 'search_by_dish' }
      format.js   
    end 
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/search.html.erb
<%= render 'homes/header' %>

<div class="body_center" >
  <div >
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10 search-field">
        <span>
          <%= form_with url: suggestions_restaurants_path, method: :get do |form| %>
          <%= form.text_field :query, id:"search-bar", placeholder: 'Search for restaurants and food', class:["serarch-input-field"] ,autocomplete:"off"%>
          <span class="icon-magnifier">  <i class="fa fa-search search-icon"></i></span>
          <% end %>
        </span>
      </div>
      <div class="col-1"></div>
    </div>
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="search-body" id="suggestions-container">
          <div >
            <h6>Recent Searches</h6>
            <div>
              <% session[:recent_search]&.each do |restaurant_id, restaurant_data| %>
              <div  class = "suggestion"data-id="<%= restaurant_data["id"] %>" >
                <b hidden><%= restaurant_data["name"] %></b>
                <span class="icon-magnifier">  <i class="fa fa-search search-icon"></i></span>
                <span><%= restaurant_data["name"] %></span>
                <small hidden><%= restaurant_data["table_name"] %></small>
              </div>
            <% end %>
            </div>
          </div>
          <div>
            <h5>Popular Cuisines</h5>
            <div class="horizontal-scroll">
              <% @categories.each do |category| %>
                <div class="scroll-content recent_search" data-id="<%= category.id %>" >
                  <small hidden >dish</small>
                  <b hidden><%= category.name %></b>
                  <p><%= category.name %></p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <div class="col-1"></div>

    </div>
    
    </div>
    
  </div>

</div>

app/views/restaurants/search_by_dish.html.erb
<div>
  <div>
    <% if @food_items.any? %>
  <div class="row">
    <% @food_items.each do |item|%>
    <div class="col-6">
      <%= link_to (restaurant_path(item.restaurant)) do%>
      <div>
        <b><%= item.restaurant.name %></b>
        <small><%= item.restaurant.area %></small>
      </div>
      <% end %>
      <hr/>
      <div class="row">
        <div class="col-9">
          <h5><%= item.name %></h5>
          <small><%= item.price%></small>
        </div>
        <div class="col-3">

        </div>
        
      </div>
    </div>
    <% end %>
  </div>
  <% else%>
  <div>
    <h6> no item found</h6>
  </div>
  <%end%>
  </div>

</div>

app/views/restaurants/search_by_restaurents.html.erb
<div>
  <div class="row">
    <div class="col-6">
      <%= link_to (restaurant_path(@restaurant)) do%>
      <div class="row">
        <div class="col-2"></div>
        <div class="col-10">
          <b> <%= @restaurant.name%></b>
          <p> <%= @restaurant.area%></p>
          <small><%= @restaurant.spaciality %></small>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<%= render 'homes/header' %>

<div class="main_body">
	<div class="restaurant">
		<div class="row">
			<div class="col-8">
				<h3><%= @restaurant.name %></h3>
			</div>
			<div>
				<%= @restaurant.spaciality %><br>
				<%= @restaurant.area %>
			</div>
		</div>
	</div>
	<div class="food_items">
		<% @food_items.each do |item| %>
		<div class="row">
			<div class="col-12">
				<h3><%= item.name %></h3>
				<h4>Rs. <%= item.price %> </h4>
				<%= item .description %> 
			</div>
		</div>
		<div>
			<% if @cart_food_item_ids.nil? || @cart_food_item_ids.empty?%>
				<div>
					<%= link_to "Add to cart", 'http://localhost:3000/cart_items?'+{item_id:item.id}.to_param, data:{ "turbo-method": :post }  %>
				</div>
			<% elsif @cart_food_item_ids.include?(item.id) %>
				<div class="row">
					<div class="col-1">
						<%= link_to "-", decrement_cart_item_path(item.id), :class => "button",data: { "turbo-method": :post }  %>
					</div>
					<div class="col-1">
						<%= CartItem.find_by(cart_id: current_user.cart.id,food_item_id: item.id).quantity %>
					</div>
					<div class="col-1">
						<%= link_to "+", increment_cart_item_path(item.id), :class => "button",data: { "turbo-method": :post }  %>
					</div>
				</div>
			<% else %>
				<div>
					<%= link_to "Add to cart", 'http://localhost:3000/cart_items?'+{item_id:item.id}.to_param, data:{ "turbo-method": :post }  %>
				</div>
			<% end %>
		</div>
		<% end %>
	</div>
</div>

app/views/restaurants/suggestions.html.erb
<div>
  <% @suggestions.each do |suggestion|%>
    <div class="row suggestion" data-id="<%= suggestion[:id] %>">
      <div class="col-1"></div>
      <%# <% binding.pry%> 
      <div class="col-11">
        <b><%= suggestion[:name]%></b>
        <br>
        <small><%= suggestion[:table_name]%></small>
      </div>

    </div>
  <% end %>
</div>