config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"

  
  # get 'search', to: 'homes#search'

  # get '', to: 'search#search', as: 'search'

  resources :homes, only: [:index] do
    collection do
      get 'filter'
      get 'select_location'
    end
  end

  devise_scope :user do
    get "user/profile" => "users#profile",as: "profile_user"
  end

  resources :users do
    resources :addresses
  end
  get '/search', to: 'restaurants#search', as: 'search_restaurants'

  resources :restaurants do 
    collection do
      get 'search'
      get 'suggestions'
      get 'search_by_restaurents'
      get 'search_by_dish'
    end
  end

  resources :cart_items do
    member do 
      post :increment
      post :decrement
    end
  end

  resources :orders do
  end

  resources :order_items do
  end


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true

  def self.ransackable_attributes(auth_object = nil)
    ["addressable_id", "addressable_type", "city", "created_at", "door_number", "id", "state", "street_area", "updated_at", "zipcode"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["addressable", "orders"]
  end
  
  scope :locations, -> {where(addressable_type: 'Restaurant').pluck(:street_area).uniq }

  has_many :orders
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at]  # Add the attributes you want to make searchable
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/attachment.rb
class ActiveStorage::Attachment < ApplicationRecord
  def self.ransackable_attributes(_auth_object = nil)
    ["blob_id", "created_at", "id"]
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["blob_id", "created_at", "id", "name", "record_id", "record_type"]
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :cart


  def self.ransackable_attributes(auth_object = nil)
    ["cart_id", "created_at", "food_item_id", "id", "quantity", "updated_at"]
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :food_items
  # has_one :image, as: :imageable, class_name: 'Picture', dependent: :destroy
  has_one :picture, as: :imageable, dependent: :destroy


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["food_items"]
  end


end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :restaurant
  belongs_to :category
  has_many   :cart_items
  has_many   :order_items
  has_one    :picture, as: :imageable

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "name", "price", "restaurant_id", "food_type", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["cart_items", "category", "restaurant"]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many   :order_items

  def self.ransackable_attributes(auth_object = nil)
    ["address_id", "created_at", "id", "total_items", "total_price", "updated_at", "user_id"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :food_item
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_one_attached :image
  belongs_to :imageable, polymorphic: true

  def self.ransackable_associations(auth_object = nil)
    ["blob", "image_attachment", "image_blob", "imageable", "record"]
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["blob_id", "created_at", "id", "name", "record_id", "record_type"]
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_one :address, as: :addressable, dependent: :destroy
  has_many :food_items, dependent: :destroy
  has_one  :picture, as: :imageable, dependent: :destroy

  scope :by_street_area, ->(location) { joins(:address).where(address: { street_area: location }).distinct }
  scope :price_range, ->(min_price, max_price) { joins(:food_items).where('food_items.price >= ? AND food_items.price <= ?', min_price, max_price) }
  scope :below_price, ->(max_price) { joins(:food_items).where('food_items.price <= ?', max_price).distinct }
  scope :newest_first, -> { order(created_at: :desc) }

  def self.ransackable_attributes(auth_object = nil)
    ["area", "created_at", "id", "name", "spaciality", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["addresses"]
  end

  def self.ransackable_attributes(auth_object = nil)
    super + ['address_id']
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable  
  
  has_many :addresses, as: :addressable
  has_one  :cart
  has_many :orders
         
         
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "name", "phone_number", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["addresses"]
  end

  

      
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @addresses= current_user.addresses
  end

  def new
    @address=current_user.addresses.new
  end
  def create
    @user = current_user  
    @address = @user.addresses.new(address_params)

    if @address.save
      redirect_to user_addresses_path(current_user) , notice: 'Address was successfully created.'
    else
      render :new
    end
  end
  
  def edit 
    @user = current_user 
    @address = @user.addresses.find(params[:id])
  end

  def update
    @user = current_user
    @address = @user.addresses.find(params[:id])

    if @address.update(address_params)
      redirect_to user_addresses_path(current_user), notice: 'Address was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user = current_user # Assuming you have a `current_user` method
    @address = @user.addresses.find(params[:id])

    if @address.destroy
      redirect_to user_path(@user), notice: 'Address was successfully deleted.'
    else
      redirect_to user_path(@user), alert: 'Failed to delete address.'
    end
  end

private

  def address_params
    params.require(:address).permit(:door_number, :street_area, :city, :state, :zipcode,:addressable_type,:addressable_id)
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/edit.html.erb
<!-- app/views/addresses/edit.html.erb -->

<h1>Edit Address</h1>


<%= form_for([current_user, @address], url: user_address_path(current_user, @address), turbo_method: :patch) do |f| %>
  <div class="field">
    <%= f.label :door_number %>
    <%= f.text_field :door_number %>
  </div>

  <div class="field">
    <%= f.label :street_area %>
    <%= f.text_field :street_area %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>

  <div class="actions">
    <%= f.submit 'Update Address' %>
  </div>
<% end %>

<%= link_to 'Cancel',  :back %>

app/views/addresses/index.html.erb
<!-- app/views/users/show.html.erb -->

<h1>User Profile</h1>
<p><strong>Name:</strong> <%= current_user.name %></p>
<p><strong>Email:</strong> <%= current_user.email %></p>

<h2>Addresses</h2>
<% if current_user.addresses.any? %>
  <ul>
    <% @addresses.each do |address| %>
      <li>
        <strong>Door.no</strong> <%= address.door_number%><br>
        <strong>Street:</strong> <%= address.street_area %><br>
        <strong>City:</strong> <%= address.city %><br>
        <strong>State:</strong> <%= address.state %><br>
        <strong>Zipcode:</strong> <%= address.zipcode %>
      </li>
      <%= link_to 'Delete', user_address_path(current_user, address), data: { turbo_method: :delete }%>
      <%= link_to 'Edit ', edit_user_address_path(current_user, address) %>
    <% end %>
  </ul>
<% else %>
  <p>No addresses found for this user.</p>
<% end %>
<%= link_to 'add new address', new_user_address_path(current_user) %>

<%= link_to 'Edit Profile', edit_user_path(current_user) %>

app/views/addresses/new.html.erb
<!-- app/views/addresses/new.html.erb -->

<h1>New Address</h1>


<%= form_for([current_user, @address]) do |f| %>
  <div class="field">
    <%= f.label :door_number %>
    <%= f.text_field :door_number %>
  </div>

  <div class="field">
    <%= f.label :streetarea %>
    <%= f.text_field :street_area %>
  </div>

  <div class="field">
  <%= f.label :city %>
  <%= f.text_field :city %>
</div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Address' %>
  </div>
<% end %>

<%= link_to 'Back', profile_user_path(current_user) %>